### ISSUE TITLE
Fix output charset

### ISSUE THREAD

**Issue by marado** [marado/dhcenters#1]

**Comment by minudika** [comment]
Can you please give some more information about this issue? Then I can give it a try :)

**Comment by marado** [comment]
@minudika Sure!

See, for instance, this line: https://github.com/marado/dhcenters/blob/master/dhcenters.csv#L43 

It looks like the file is trying to display iso-latin1 text as utf8 or vice-versa, something that probably can be easily fixed with iconv, but I had no time to look at it. In any case, the description for the issue should be something like "some characters in the generated CSV file are displayed with an incorrect charset, at least when seen in github's viewer".

Let me know if you need more details.
